language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm  
  - hhvm-nightly
  
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script:
  - phpunit tests/webignition/Tests/Url/ClearPropertiesTest.php
  
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm-nightly
